name: Frontend Container Deployment to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

env:
  AZURE_RESOURCE_GROUP: 'demo-rg'
  AZURE_APP_SERVICE: 'demo-frontend-app' 
  ACR_NAME: 'chasDemoACR'
  IMAGE_NAME: 'frontend-app'
  DOCKERFILE_PATH: 'frontend/Dockerfile'
  WEBSITES_PORT: 80 
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # Logga in i Azure denna gång använder vi Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Logga in i Azure Container Registry (ACR)
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      # Bygg och tagga Docker-imagen
      - name: Build and Tag Image
        run: |
          docker build \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --context frontend \ 
            -f ${{ env.DOCKERFILE_PATH }} .

      # Pusha imagen till ACR
      - name: Push Image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Deploy till Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          configuration-settings: |
            DOCKER_REGISTRY_SERVER_URL: https://${{ env.ACR_NAME }}.azurecr.io
            WEBSITES_PORT: ${{ env.WEBSITES_PORT }}