name: Migrate Azure Db with Flyway

on:
  workflow_dispatch: {}

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flyway
        run: |
          FLYWAY_VERSION=10.16.0
          curl -L "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.zip" --output flyway.zip
          unzip flyway.zip
          echo "$(pwd)/flyway-${FLYWAY_VERSION}" >> $GITHUB_PATH

      - name: Run Flyway migration
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          flyway migrate